### ISSUE TITLE
Says connected but nothing in table

### ISSUE THREAD

**Issue by dac2020** [ncd-io/Mosquitto_Subscriber_MySQL_Publisher#3]
I followed this;
https://ncd.io/log-mqtt-gateway-data-to-mysql-database/

It was late so I fired this up and left the office. This morning, I see nothing in the table.
When I stopped the script, I got this;
MQTT Client Connected
MySQL Client Connected
MQTT Client Connected
MySQL Client Connected
^CTraceback (most recent call last):
  File "mqtt_sub_mysql_pub.py", line 118, in <module>
    client.loop_forever()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 1773, in loop_forever
    self._reconnect_wait()
  File "/usr/local/lib/python3.6/site-packages/paho/mqtt/client.py", line 3612, in _reconnect_wait
    time.sleep(min(remaining, 1))
KeyboardInterrupt

OS is Centos 7.9, running latest MariaDB and Python 3.6.8.

I looked in the logs to see if I could find something but there is nothing.
I tried the mqtt account and the root account and both can access the db service which is local.

Since I don't know much about Python, figured I should ask before trying things I find on the Internet as I don't want to break the system.

Not sure what else to provide at the moment.

**Comment by telliottosceola** [comment]
@dac2020,

To be 100% honest I put this together more than 2 years ago.  I ran it on Mac OS.  I'm not sure about compatibility issues on CentOS but it looks to me like the failure was a result of the Python MQTT Client library which attempted to reconnect after a dropped connection. 

I would run the script again, make sure your MQTT Gateway is connected(flashing Green LED) then press the RST button on your sensor to force a transmission to see if anything is logged to the SQL database.

**Comment by dac2020** [comment]
I think I am using the wrong script then :). 
I have no LED, it's just a centos server running MQTT.

I can see the messages coming from the devices to the MQTT server, they just aren't getting into the database.
Your script does mention making sure to get the ID of MQTT gateway but I've not found any such thing.

User variable for Gateway ID
myGatewayID = ""

Your script has a MAC address so I put the servers MAC address in this.

I guess I need to hunt down something more current?

Thanks for your input.

**Comment by telliottosceola** [comment]
Are you using our MQTT Gateway and wireless sensors?  If not what is the device publishing telemetry to the Mosquitto broker?

**Comment by dac2020** [comment]
I didn't even know of a gateway, I just came across the page while searching on how I can log all mqtt broker messages to db.
I'm using a centos server with mosquitto and some tasmota relay boards.

**Comment by dac2020** [comment]
I went back to the page and looked and now see you offer your own hardware which explains why this might not work then.

**Comment by telliottosceola** [comment]
It would certainly require some modifications.
